# Generated by Django 5.2.7 on 2025-10-11 10:27

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("attendance", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="attendancerecord",
            options={
                "ordering": ["-date", "-check_in_time"],
                "verbose_name": "Bản ghi chấm công",
                "verbose_name_plural": "Bản ghi chấm công",
            },
        ),
        migrations.AlterModelOptions(
            name="employee",
            options={
                "ordering": ["employee_id"],
                "verbose_name": "Nhân viên",
                "verbose_name_plural": "Nhân viên",
            },
        ),
        migrations.AddField(
            model_name="employee",
            name="address",
            field=models.TextField(blank=True, null=True, verbose_name="Địa chỉ"),
        ),
        migrations.AddField(
            model_name="employee",
            name="date_of_birth",
            field=models.DateField(blank=True, null=True, verbose_name="Ngày sinh"),
        ),
        migrations.AddField(
            model_name="employee",
            name="gender",
            field=models.CharField(
                choices=[("M", "Nam"), ("F", "Nữ"), ("O", "Khác")],
                default="O",
                max_length=1,
                verbose_name="Giới tính",
            ),
        ),
        migrations.AddField(
            model_name="employee",
            name="join_date",
            field=models.DateField(
                default=django.utils.timezone.now, verbose_name="Ngày vào làm"
            ),
        ),
        migrations.AddField(
            model_name="employee",
            name="phone_number",
            field=models.CharField(
                blank=True, max_length=15, null=True, verbose_name="Số điện thoại"
            ),
        ),
        migrations.AlterField(
            model_name="attendancerecord",
            name="check_in_photo",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="attendance_photos/",
                verbose_name="Ảnh check-in",
            ),
        ),
        migrations.AlterField(
            model_name="attendancerecord",
            name="check_in_time",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Thời gian check-in"
            ),
        ),
        migrations.AlterField(
            model_name="attendancerecord",
            name="check_out_photo",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="attendance_photos/",
                verbose_name="Ảnh check-out",
            ),
        ),
        migrations.AlterField(
            model_name="attendancerecord",
            name="check_out_time",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Thời gian check-out"
            ),
        ),
        migrations.AlterField(
            model_name="attendancerecord",
            name="date",
            field=models.DateField(auto_now_add=True, verbose_name="Ngày"),
        ),
        migrations.AlterField(
            model_name="attendancerecord",
            name="employee",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="attendance.employee",
                verbose_name="Nhân viên",
            ),
        ),
        migrations.AlterField(
            model_name="attendancerecord",
            name="note",
            field=models.TextField(blank=True, null=True, verbose_name="Ghi chú"),
        ),
        migrations.AlterField(
            model_name="attendancerecord",
            name="status",
            field=models.CharField(
                choices=[
                    ("ON_TIME", "Đúng giờ"),
                    ("LATE", "Đi muộn"),
                    ("EARLY", "Về sớm"),
                    ("ABSENT", "Vắng mặt"),
                ],
                max_length=20,
                verbose_name="Trạng thái",
            ),
        ),
        migrations.AlterField(
            model_name="employee",
            name="department",
            field=models.CharField(
                default="Chưa phân công", max_length=100, verbose_name="Phòng ban"
            ),
        ),
        migrations.AlterField(
            model_name="employee",
            name="employee_id",
            field=models.CharField(
                max_length=20, unique=True, verbose_name="Mã nhân viên"
            ),
        ),
        migrations.AlterField(
            model_name="employee",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="Đang làm việc"),
        ),
        migrations.AlterField(
            model_name="employee",
            name="position",
            field=models.CharField(
                default="Nhân viên", max_length=100, verbose_name="Chức vụ"
            ),
        ),
    ]
