# Generated by Django 5.2.7 on 2025-10-11 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("attendance", "0002_alter_attendancerecord_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="current_status",
            field=models.CharField(
                choices=[
                    ("IN_OFFICE", "Đang trong ca làm việc"),
                    ("OUT_OFFICE", "Đã check-out"),
                    ("NOT_IN", "Chưa check-in"),
                ],
                default="NOT_IN",
                max_length=20,
                verbose_name="Trạng thái hiện tại",
            ),
        ),
        migrations.AddField(
            model_name="employee",
            name="work_status",
            field=models.CharField(
                choices=[
                    ("WORKING", "Đang làm việc tại công ty"),
                    ("ON_LEAVE", "Đang nghỉ phép"),
                    ("TERMINATED", "Đã nghỉ việc"),
                ],
                default="WORKING",
                max_length=20,
                verbose_name="Trạng thái làm việc",
            ),
        ),
        migrations.AlterField(
            model_name="employee",
            name="is_active",
            field=models.BooleanField(
                default=True, verbose_name="Tài khoản đang hoạt động"
            ),
        ),
    ]
