# Generated by Django 5.2.7 on 2025-10-11 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("attendance", "0003_employee_current_status_employee_work_status_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employee",
            name="current_status",
            field=models.CharField(
                choices=[
                    ("IN_OFFICE", "Đang trong ca làm việc"),
                    ("OUT_OFFICE", "Đã check-out"),
                    ("NOT_IN", "Chưa check-in"),
                ],
                default="NOT_IN",
                editable=False,
                max_length=20,
                verbose_name="Trạng thái hiện tại",
            ),
        ),
    ]
