# Generated by Django 5.2.5 on 2025-12-23 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("attendance", "0005_department"),
    ]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="expo_push_token",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Expo Push Token"
            ),
        ),
    ]
