# Generated by Django 5.2.7 on 2026-01-06 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("attendance", "0007_alter_employee_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="email",
            field=models.EmailField(
                blank=True, max_length=254, null=True, verbose_name="Email"
            ),
        ),
        migrations.AddField(
            model_name="employee",
            name="first_name",
            field=models.CharField(default="", max_length=50, verbose_name="Tên"),
        ),
        migrations.AddField(
            model_name="employee",
            name="last_name",
            field=models.CharField(default="", max_length=50, verbose_name="Họ"),
        ),
    ]
