# Generated by Django 5.2.5 on 2026-02-05 09:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("attendance", "0008_employee_email_employee_first_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employee",
            name="department",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="employees",
                to="attendance.department",
                verbose_name="Phòng ban",
            ),
        ),
    ]
