# Generated by Django 5.2.5 on 2026-03-09 14:27

from django.db import migrations
from pgvector.django import VectorExtension


class Migration(migrations.Migration):

    dependencies = [
        ("attendance", "0009_department_fk"),
    ]

    operations = [
        VectorExtension()
    ]
