# Generated by Django 5.2.5 on 2026-03-09 14:28

import django.db.models.deletion
import pgvector.django.vector
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("attendance", "0010_pgvector_extension"),
    ]

    operations = [
        migrations.CreateModel(
            name="EmployeeFaceEmbedding",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "embedding",
                    pgvector.django.vector.VectorField(
                        dimensions=512, verbose_name="Face Embedding Vector"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="face_embeddings_vector",
                        to="attendance.employee",
                        verbose_name="Nhân viên",
                    ),
                ),
            ],
            options={
                "verbose_name": "Face Embedding",
                "verbose_name_plural": "Face Embeddings",
            },
        ),
    ]
